### ISSUE TITLE
ci是否有问题？

### ISSUE THREAD

**Issue by fwon** [fis-components/react#1]
把目标文件打包到dist, 但是本地通过fis3 install安装后本地多了很多冗余文件（相比之前）。
特别是在用mod.js等加载器的时候，就会引入lib的n个文件。
难道fis-components不是只应该保存dist下的目标文件吗？或者这个问题有什么解决方法？

**Comment by oxUnd** [comment]
@fwon 应该是 id -> url 的映射（map）配置吧？这个没法减掉

**Comment by fwon** [comment]
@xiangshouding 之前的fis-components 应该是只是保留了合并后的文件吧。 例如 https://github.com/fis-components/react-redux  要不怎么直接require到dist下的文件？

**Comment by 2betop** [comment]
是这样的，之所以又把 lib 放回来，是有些包直接 `require('react/lib/xxxx')` 碰到这种就跪了。没辙，就放回来 lib 吧，同时也把 dist 的放过来了，提供选择。你可以通过以下方式使用 dist 的版本。

```
// 调整下顺序，让 commonjs 先来。
fis.unhook('components');
fis.hook('commonjs', {
  paths: {
    'react': '/components/react/dist/react.js'
  }
})
// 再启用 components 插件，让 commonjs 插件优先。
fis.hook('components');
```

另外：react 换成 lib 版本是 >0.14.3 的版本才这样，你可以考虑用老的版本。

**Comment by 2betop** [comment]
fis 合并并不难。

```
fis.match('::package', {
  packager: fis.plugin('deps-pack', {
    'pkg/react.js': [
      '/components/react/react.js', // react.js
      '/components/react/react.js:deps' // 以及它的所有依赖。
    ]
  })
})
```

**Comment by fwon** [comment]
感觉这个坑不小啊，好多组件竟然都是webpack打包出来的 https://github.com/fis-components/react-redux/blob/master/react-redux.js

**Comment by 2betop** [comment]
react-redux  这种可以用合并版本，因为没有库直接用 `require('react-redux/lib/xxx')` 的情况。

对了，fis3 还支持按需编译，像这种组件库代码这么多的情况，一定得开启。设置 `project.files` 入口文件即可。

**Comment by 2betop** [comment]
等 react 1.0 吧，那个时候换回只保留 dist 的模式，主要是这个库现在没法使 https://www.npmjs.com/package/react-tap-event-plugin

**Comment by 2betop** [comment]
fuck [react-tap-event-plugin](https://www.npmjs.com/package/react-tap-event-plugin) 还是继续用 dist 的版本吧。
